# Generated by Django 4.2.1 on 2024-05-27 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='modelo1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Xi', models.FloatField()),
                ('delta', models.FloatField()),
                ('NumeroIteraciones', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='modelo2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Xi', models.FloatField()),
                ('tolerancia', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='modelo3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Xi', models.FloatField()),
                ('Xf', models.FloatField()),
                ('tolerancia', models.FloatField()),
                ('NumeroIteraciones', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='modelo4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Xi', models.FloatField()),
                ('tolerancia', models.FloatField()),
                ('NumeroIteraciones', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='modelo5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Xi', models.FloatField()),
                ('tolerancia', models.FloatField()),
                ('NumeroIteraciones', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='modelo6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('A', models.TextField()),
                ('n', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='modelo7',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('A', models.TextField()),
                ('b', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='modelo8',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('A', models.TextField()),
                ('b', models.TextField()),
                ('tolerancia', models.FloatField()),
                ('NumeroIteraciones', models.IntegerField()),
            ],
        ),
    ]
