# Generated by Django 4.2.1 on 2024-05-27 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelo1',
            name='funcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modelo2',
            name='funcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modelo3',
            name='funcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modelo4',
            name='funcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modelo4',
            name='g',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modelo5',
            name='funcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modelo6',
            name='A',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modelo7',
            name='A',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modelo7',
            name='b',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modelo8',
            name='A',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modelo8',
            name='b',
            field=models.TextField(blank=True, null=True),
        ),
    ]
