# Generated by Django 4.2.1 on 2024-05-27 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methods', '0002_modelo1_funcion_modelo2_funcion_modelo3_funcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelo2',
            name='Xf',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modelo2',
            name='Xi',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
