# Generated by Django 4.2.1 on 2024-05-27 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methods', '0003_modelo2_xf_alter_modelo2_xi'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelo2',
            name='NumeroIteraciones',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
